//
// Created by mamin on 2/9/2021.
//
#ifndef EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_QUERIES_ALIGNMENT_OF_H
#define EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_QUERIES_ALIGNMENT_OF_H

#endif //EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_QUERIES_ALIGNMENT_OF_H
