//
// Created by admin on 2021/2/9.
//

#ifndef EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_QUERIES_RANK_H
#define EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_QUERIES_RANK_H

#endif //EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_QUERIES_RANK_H
