//
// Created by admin on 2021/2/9.
//

#ifndef EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_ARRAYS_REMOVE_ALL_EXTENTS_H
#define EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_ARRAYS_REMOVE_ALL_EXTENTS_H

#endif //EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_ARRAYS_REMOVE_ALL_EXTENTS_H
