//
// Created by admin on 2021/2/9.
//

#ifndef EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_OPERATIONS_HAS_VIRTUAL_DESTRUCTOR_H
#define EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_OPERATIONS_HAS_VIRTUAL_DESTRUCTOR_H

#endif //EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_OPERATIONS_HAS_VIRTUAL_DESTRUCTOR_H
