//
// Created by admin on 2021/2/9.
//

#ifndef EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_OPERATIONS_IS_MOVE_CONSTRUCTIBLE_H
#define EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_OPERATIONS_IS_MOVE_CONSTRUCTIBLE_H

#endif //EXERCISE_MOSCOW_SRC_MOSCOW_TRAITS_OPERATIONS_IS_MOVE_CONSTRUCTIBLE_H
